use_frameworks!
inhibit_all_warnings!

# Uncomment this line to define a global platform for your project
  platform :ios, '9.0'

target 'AirbnbClone' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MyProgram
    pod 'DoubleConversion', podspec: '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
    pod 'Folly', podspec: '../node_modules/react-native/third-party-podspecs/Folly.podspec'
    pod 'GLog', podspec: '../node_modules/react-native/third-party-podspecs/GLog.podspec'
   pod 'Yoga', path: "../node_modules/react-native/ReactCommon/yoga/yoga.podspec"
   pod 'React', path: '../node_modules/react-native', :subspecs => [
  'Core',
  'CxxBridge',
  'DevSupport',
  'RCTActionSheet',
  'RCTGeolocation',
  'RCTImage',
  'RCTLinkingIOS',
  'RCTNetwork',
  'RCTSettings',
  'RCTText',
  'RCTVibration',
  'RCTWebSocket'
  ]

  pod 'GoogleMaps'



end
source 'https://github.com/CocoaPods/Specs.git'


