

# Uncomment this line to define a global platform for your project
  platform :ios, '9.0'

target 'AirbnbClone' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MyProgram
   pod 'Yoga', path: "../node_modules/react-native/ReactCommon/yoga/Yoga.podspec"
   pod 'React', path: '../node_modules/react-native', :subspecs => [
  'Core'
  'DevSupport',
  'RCTActionSheet',
  'RCTGeolocation',
  'RCTImage',
  'RCTLinkingIOS',
  'RCTNetwork',
  'RCTSettings',
  'RCTText',
  'RCTVibration',
  'RCTWebSocket'
  ]

  pod 'GoogleMaps'



end
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
